[project]
name = "alphadev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flax>=0.12.4",
    "jax[cuda12]>=0.9.0.1",
    "numpy>=2.3.5",
    "optax>=0.2.6",
]
